### ISSUE TITLE
Extra Branches/Step Inconsistencies

### ISSUE THREAD

**Issue by dcalise** [kentcdodds/static-testing-tools#12]
There seems to be some extra branches in the repo:
![image](https://user-images.githubusercontent.com/2141172/77826430-9e11a680-70e5-11ea-9b01-464e7614aedc.png)

Also it seems like some of the branches are not matching up with the videos. For example, I checked out `tjs/step-11` and it has the completed code for 11, 12, and 13.

**Comment by kentcdodds** [comment]
Hi @dcalise,

You are correct. There are lots of branches and they don't always match the order of the videos. This is why it's important to click the link below the video to see the diff.
