### ISSUE TITLE
[INFO] [CHORE] husky is updated  | Ideology is same

### ISSUE THREAD

**Issue by nikhilkuyya** [kentcdodds/static-testing-tools#22]
Just suggestions: 

- husky now creating the new .husky folder
- and pre-commit also added under .husky

may be we would like to update the testing video for husky or docs here.
But your suggestions on husky as tool ideology is not changed.

**Comment by kentcdodds** [comment]
Yeah, I'm aware. There is a notice in the description of the video and if I ever do update the videos I'll be sure to update all dependencies as well. Currently I have no plans to update the videos. Thanks though!
