### ISSUE TITLE
lint-staged only runs ESLint on .js files

### ISSUE THREAD

**Issue by LarsJK** [kentcdodds/static-testing-tools#3]
Shouldn't ESLint run on at least jsx files as well?

https://github.com/kentcdodds/static-testing-tools/blob/860492ad3fa95a8a81a8a7d86f30d9cb3e2fac22/08-auto-format-all-files-and-validate-relevant-files-in-a-precommit-script-with-lint-staged/.lintstagedrc#L3

**Comment by kentcdodds** [comment]
I guess. I didn't think about it because I really don't like the `.jsx` extension at all.

It's only included in the other glob because I included everything that prettier supports in there 🤷‍♂️
