### ISSUE TITLE
lint-staged and husky updates

### ISSUE THREAD

**Issue by thall1961** [kentcdodds/static-testing-tools#4]
You're probably aware, but thought I'd pass along:

With lint-staged, it looks like `"linters": {}` is no longer needed.  [Going straight to the commands works](https://github.com/okonet/lint-staged#configuration)

Husky shows a warning that putting hooks in npm scripts will be deprecated.  They offer a few other ways - [e.g. putting them in package.json](https://github.com/dhicorp/dhi-starter-marketing-site)

**Comment by kentcdodds** [comment]
Thanks Tom. I'm working on updating this currently. Hopefully the recordings will be updated soon.

**Comment by koreyboone** [comment]
Any update on the updates? Just bought a license and this took me a little bit to figure out lol

**Comment by kentcdodds** [comment]
Over half of the re-recording (and new recordings) are finished, but they all still need to be edited.
